### ISSUE TITLE
Installation failed for blender v2.82.7

### ISSUE THREAD

**Issue by zruan** [PabloEnmanuelRamos/BioBlender21#2]
Hi,

I recently noticed that bioblender supports blender 2.8 now. So I followed the instructions to clone the code and make a soft link to the addOn folder. The addOn does appear in the blender menu. However, when I check the box it errors out with the following message:

```Traceback (most recent call last):
  File "/home/zruan/software/blender/blender-2.82a-linux64/2.82/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/zruan/.config/blender/2.82/scripts/addons/BioBlender21/__init__.py", line 38, in <module>
    from .BB2_GUI_PDB_IMPORT import *
  File "/home/zruan/.config/blender/2.82/scripts/addons/BioBlender21/BB2_GUI_PDB_IMPORT.py", line 28, in <module>
    from . import BB2_PANEL_VIEW as panel
  File "/home/zruan/.config/blender/2.82/scripts/addons/BioBlender21/BB2_PANEL_VIEW.py", line 412
    def launch(exeName, async=False):
                            ^
SyntaxError: invalid syntax
```

I see in the instructions that bioblender requires python 3.5.3. Could this be the issue? In the python console of blender, I see it is using python 3.7.4. I don't know a way to change the python version inside blender.

Thanks,
Zheng

**Comment by MonZop** [comment]
Hi, I suspect you misnterpreted the announcement. BioBlender is at this time working for Blender 2.79.
We are preparing a version for Blender 2.8, but it will need some more work, and we cannot say when exactly it will be available. Please use Blender 2.79, or... just wait!
Thanks
